hook_before_setup_plugin = """set updatetime=1000
set timeoutlen=300
set wildmenu
set lazyredraw
let &t_ut=''"""
hook_after_setup_plugin = ""
# if use plug,set to 1 to improve bootstrap
make_json = 0
# level 0 pure: no plugin and module
# level 1 basic: theme statusline tabline
# level 2 normal: complete search file-explore git comment floaterm e.g.
# level 3 enhanced: motion multi-line align jump
config_level = 3
ovim_plug_manager = "dein"

[var]
root_marker = [".git",".hg",".svn",".root",".project",
                "compile_commands.json","CMakeLists.txt",
                "Makefile","makefile"]

[plugins."tweekmonster/startuptime.vim"]
level = 0
repo = "tweekmonster/startuptime.vim"
on = "StartupTime"
on_cmd = "StartupTime"

[plugins."dstein64/vim-startuptime"]
level = 0
repo = "dstein64/vim-startuptime"
on = "StartupTime"
on_cmd = "StartupTime"
if = 0

[plugins."wsdjeg/dein-ui.vim"]
level = 0
repo = "wsdjeg/dein-ui.vim"
if = "g:ovim_plug_manager ==# 'dein'"
on_cmd = "DeinUpdate"

[plugins."haya14busa/dein-command.vim"]
level = 0
repo = "haya14busa/dein-command.vim"
if = "g:ovim_plug_manager ==# 'dein'"
on_cmd = "Dein"

[plugins."arakashic/nvim-colors-solarized"]
level = 1
repo = "arakashic/nvim-colors-solarized"
if = 0

# colorscheme gruvbox
[plugins."morhetz/gruvbox"]
level = 1
repo = "morhetz/gruvbox"

[plugins."miconda/lucariox.vim"]
level = 1
repo = "miconda/lucariox.vim"

# colorscheme oceanic_material
[plugins."hardcoreplayers/oceanic-material"]
level = 1
repo = "hardcoreplayers/oceanic-material"
# colorscheme OceanicNext
[plugins."mhartington/oceanic-next"]
level = 1
repo = "mhartington/oceanic-next"

# set background=dark
# colorscheme one
[plugins."rakr/vim-one"]
level = 1
repo = "rakr/vim-one"

#" Dark
#set background=dark
#colorscheme vim-material

#" Palenight
#let g:material_style='palenight'
#set background=dark
#colorscheme vim-material

#" Oceanic
#let g:material_style='oceanic'
#set background=dark
#colorscheme vim-material

#" Light
#set background=light
#colorscheme vim-material
#airline
#let g:airline_theme='material'
[plugins."hzchirs/vim-material"]
level = 1
repo = "hzchirs/vim-material"

[plugins."https://gitee.com/yelgors/vim-togglemouse.git"]
level = 1
repo = "https://gitee.com/yelgors/vim-togglemouse.git"
branch = "dev"
rev = "dev"
hook_post_source = """call toggle_mouse#map("<F7>")
let g:space_key_map['<F7>'] = ['<F7>','Toogle Mouse(todo)']"""

[plugins."Shougo/defx.nvim"]
level = 2
repo = "Shougo/defx.nvim"
do = ":UpdateRemotePlugins"
on_cmd = "Defx"
hook_add = "source $OVIM_ROOT_PATH/keymaps/defx.add.vim"
hook_post_source = "source $OVIM_ROOT_PATH/plugins/defx.post-source.vim"

[plugins."kristijanhusak/defx-git"]
level = 2
repo = "kristijanhusak/defx-git"

[plugins."kristijanhusak/defx-icons"]
level = 2
repo = "kristijanhusak/defx-icons"
on_source = [ "defx.nvim",]

[plugins."scrooloose/nerdtree"]
level = 3
repo = "scrooloose/nerdtree"
on = [ "NERDTreeToggle", "NERDTree",]
on_cmd = [ "NERDTreeToggle", "NERDTree",]
hook_add = "source $OVIM_ROOT_PATH/plugins/nerdtree.vim"
if = 0

[plugins."roxma/nvim-yarp"]
level = 3
repo = "roxma/nvim-yarp"
if = "!has('nvim')"

[plugins."roxma/vim-hug-neovim-rpc"]
level = 3
repo = "roxma/vim-hug-neovim-rpc"
if = "!has('nvim')"

[plugins."vim-airline/vim-airline"]
level = 2
repo = "vim-airline/vim-airline"
hook_source = "source $OVIM_ROOT_PATH/plugins/airline.vim"
if = 0

[plugins."vim-airline/vim-airline-themes"]
level = 1
repo = "vim-airline/vim-airline-themes"
if = 0

[plugins."glepnir/spaceline.vim"]
level = 1
repo = "glepnir/spaceline.vim"
hook_source = "source $OVIM_ROOT_PATH/plugins/spaceline.source.vim"

[plugins."ryanoasis/vim-devicons"]
level = 1
repo = "ryanoasis/vim-devicons"

[plugins."itchyny/lightline.vim"]
level = 2
repo = "itchyny/lightline.vim"
if = 0

[plugins."hardcoreplayers/vim-buffet"]
level = 2
repo = "hardcoreplayers/vim-buffet"
on_event = [ "VimEnter", "GUIEnter",]
hook_source = "source $OVIM_ROOT_PATH/plugins/buffet.vim"
if = 0

[plugins."pacha/vem-tabline"]
level = 2
repo = "pacha/vem-tabline"
on_event = [ "BufRead", "BufAdd", "BufNew",]
hook_source = "source $OVIM_ROOT_PATH/plugins/vem-tabline.vim"

[plugins."bling/vim-bufferline"]
level = 1
repo = "bling/vim-bufferline"
on_event = [ "CursorHold"]
if = 0
hook_source = """  let g:bufferline_echo = 1
"""

# tab无编号
[plugins."ap/vim-buftabline"]
level = 1
repo = "ap/vim-buftabline"
on_event = [ "VimEnter",]
hook_source = "source $OVIM_ROOT_PATH/plugins/buftabline.vim"
if = 0

[plugins."Yggdroot/indentLine"]
level = 3
repo = "Yggdroot/indentLine"
hook_source = "source $OVIM_ROOT_PATH/plugins/indentLine.vim"
on_event = [ "BufReadPost", "BufWritePost",]

[plugins."scrooloose/nerdcommenter"]
level = 3
repo = "scrooloose/nerdcommenter"
hook_add = "source $OVIM_ROOT_PATH/plugins/nerdcomment.vim"
on = [ "<Plug>NERDCommenterComment", "<Plug>NERDCommenterNested", "<Plug>NERDCommenterToggle",
        "<Plug>NERDCommenterMinimal", "<Plug>NERDCommenterInvert", "<Plug>NERDCommenterSexy",
        "<Plug>NERDCommenterYank", "<Plug>NERDCommenterToEOL", "<Plug>NERDCommenterAppend",
        "<Plug>NERDCommenterAltDelims", "<Plug>NERDCommenterAlignLeft",
        "<Plug>NERDCommenterAlignBoth", "<Plug>NERDCommenterUncomment",]
on_map = { nv = "<Plug>NERDCommenter" }
on_func = "NERDComment"

[plugins."majutsushi/tagbar"]
level = 3
repo = "majutsushi/tagbar"
on = [ "Tagbar", "TagbarToggle",]
on_cmd = [ "Tagbar",]
hook_add = "source $OVIM_ROOT_PATH/plugins/tarbar.vim"

[plugins."jiangmiao/auto-pairs"]
level = 3
repo = "jiangmiao/auto-pairs"
hook_source = "source $OVIM_ROOT_PATH/plugins/auto-pairs.vim"
on_event = [ "BufReadPost", "BufWritePost",]

[plugins."SirVer/ultisnips"]
level = 3
repo = "SirVer/ultisnips"
hook_source = "source $OVIM_ROOT_PATH/plugins/ultisnips.vim"
on_event = [ "VimEnter",]

[plugins."honza/vim-snippets"]
level = 3
repo = "honza/vim-snippets"
on_event = [ "VimEnter",]

[plugins."chiel92/vim-autoformat"]
level = 3
repo = "chiel92/vim-autoformat"
on = "Autoformat"
on_cmd = "Autoformat"
hook_add = "source $OVIM_ROOT_PATH/plugins/autoformat.vim"

[plugins."skywind3000/asyncrun.vim"]
level = 3
repo = "skywind3000/asyncrun.vim"
hook_add = "source $OVIM_ROOT_PATH/plugins/asyncrun.vim"
on = [ "AsyncRun",]
on_cmd = [ "AsyncRun",]
on_func = ["asyncrun#"]

[plugins."skywind3000/asynctasks.vim"]
level = 3
repo = "skywind3000/asynctasks.vim"
hook_add = "source $OVIM_ROOT_PATH/plugins/asynctasks.add.vim"
on_cmd = ["AsyncTask","AsyncTaskEdit","AsyncTaskMacro","AsyncTaskProfile"]
on = ["AsyncTask","AsyncTaskEdit","AsyncTaskMacro","AsyncTaskProfile"]


[plugins."pseewald/vim-anyfold"]
level = 3
repo = "pseewald/vim-anyfold"
hook_source = "source $OVIM_ROOT_PATH/plugins/fold.vim"
on_event = [ "BufReadPost", "BufWritePost",]

[plugins."roxma/vim-paste-easy"]
level = 2
repo = "roxma/vim-paste-easy"
on_event = [ "InsertEnter",]

[plugins."tpope/vim-surround"]
level = 3
repo = "tpope/vim-surround"
on_event = [ "VimEnter",]

[plugins."ludovicchabant/vim-gutentags"]
level = 3
repo = "ludovicchabant/vim-gutentags"
hook_source = "source $OVIM_ROOT_PATH/plugins/gutentags.source.vim"
on_cmd = ['GutentagsUpdate','GutentagsToggleEnabled','GutentagsToggleTrace']
on_event = [ "VimEnter",]
hook_post_source = 'source $OVIM_ROOT_PATH/plugins/gutentags.post-source.vim'

[plugins."skywind3000/gutentags_plus"]
level = 2
repo = "skywind3000/gutentags_plus"
on_event = [ "VimEnter",]
hook_source = 'let g:gutentags_plus_nomap = 1'

[plugins."mhinz/vim-signify"]
level = 2
repo = "mhinz/vim-signify"
hook_add = "source $OVIM_ROOT_PATH/plugins/signify.vim"
hook_post_source = "SignifyEnable"
on = [ "SignifyDiff", "SignifyEnable", "SignifyEnableAll", "SignifyToggle",]
on_cmd = [ "SignifyDiff", "SignifyEnable", "SignifyEnableAll", "SignifyToggle",]
on_event = [ "BufReadPost", "BufWritePost",]

[plugins."tpope/vim-fugitive"]
level = 2
repo = "tpope/vim-fugitive"
hook_source = "source $OVIM_ROOT_PATH/plugins/fugitive.source.vim"
on = ["Git","G"]
on_cmd = ["Git","G"]
on_event = ["VimEnter"]

[plugins."rhysd/committia.vim"]
level = 2
repo = "rhysd/committia.vim"
for = ['gitcommit','gitrebase',"vim-plug"]
on_ft = ['gitcommit','gitrebase']
on_path = ["COMMIT_EDITMSG","MERGE_MSG"]

[plugins."liuchengxu/vim-which-key"]
level = 2
repo = "liuchengxu/vim-which-key"
hook_post_source = "source $OVIM_ROOT_PATH/plugins/vim-which-key.vim"

[plugins."voldikss/vim-floaterm"]
level = 2
repo = "voldikss/vim-floaterm"
hook_add = "source $OVIM_ROOT_PATH/plugins/floaterm.vim"
on = [ "FloatermToggle", "FloatermPrev", "FloatermNext", "FloatermNew",
        "FloatermFirst", "FloatermLast", "FloatermKill",]
on_cmd = [ "FloatermToggle", "FloatermPrev", "FloatermNext", "FloatermNew",
        "FloatermFirst", "FloatermLast", "FloatermKill",]

[plugins."liuchengxu/vista.vim"]
level = 2
repo = "liuchengxu/vista.vim"
hook_add = "source $OVIM_ROOT_PATH/plugins/vista.vim"
on = [ "Vista", "Vista!", "Vista!!",]
on_cmd = [ "Vista", "Vista!", "Vista!!",]


[plugins."glepnir/dashboard-nvim"]
level = 2
repo = "glepnir/dashboard-nvim"
hook_source = "source $OVIM_ROOT_PATH/plugins/dashboard.vim"

[plugins."junegunn/vim-easy-align"]
level = 3
repo = "junegunn/vim-easy-align"
on_map = [ "<Plug>(EasyAlign)",]
on = [ "<Plug>(EasyAlign)",]
hook_add = "xmap ga <Plug>(EasyAlign)\nnmap ga <Plug>(EasyAlign)\n"

[plugins."godlygeek/tabular"]
level = 3
repo = "godlygeek/tabular"
on = ["Tabularize","Tab"]
on_cmd = ["Tabularize","Tab"]

[plugins."rhysd/accelerated-jk"]
level = 2
repo = "rhysd/accelerated-jk"
on = [ "<Plug>(accelerated_jk_gj)", "<Plug>(accelerated_jk_gk)",]
on_map = [ "<Plug>(accelerated",]
on_event = ["VimEnter"]
hook_source = "nmap j <Plug>(accelerated_jk_gj)\nnmap k <Plug>(accelerated_jk_gk)\n"

[plugins."junegunn/vim-peekaboo"]
level = 3
repo = "junegunn/vim-peekaboo"
on_event = [ "VimEnter",]
hook_post_source = 'call peekaboo#on()'

[plugins."easymotion/vim-easymotion"]
level = 3
repo = "easymotion/vim-easymotion"
on_event = [ "VimEnter",]
# hook_source = """let g:leader_key_map[","] = 'EasyMotion'"""
hook_source = """
call ovim#utils#recursive_update(g:leader_key_map,{g:mapleader:'EasyMotion'})
"""

[plugins."junegunn/vim-after-object"]
level = 3
repo = "junegunn/vim-after-object"
hook_post_source = """call after_object#enable('=',':','#',' ')"""
on_event = [ "VimEnter",]

[plugins."cespare/vim-toml"]
level = 2
repo = "cespare/vim-toml"

[plugins."elzr/vim-json"]
level = 2
repo = "elzr/vim-json"

[plugins."mg979/vim-visual-multi"]
level = 3
repo = "mg979/vim-visual-multi"
on_event = [ "VimEnter",]

[plugins."mbbill/undotree"]
level = 3
repo = "mbbill/undotree"
hook_add = """nnoremap <leader>u :UndotreeToggle<cr>
let g:leader_key_map.u = '撤销'"""
on = [ "UndotreeToggle",]
on_cmd = [ "UndotreeToggle",]

[plugins."pechorin/any-jump.vim"]
level = 3
repo = "pechorin/any-jump.vim"
on = [ "AnyJump", "AnyJumpVisual", "AnyJumpBack", "AnyJumpLastResults",]
on_cmd = [ "AnyJump", "AnyJumpVisual", "AnyJumpBack", "AnyJumpLastResults",]
hook_add = "source $OVIM_ROOT_PATH/plugins/any-jump.vim"

[plugins."Shougo/echodoc.vim"]
level = 3
repo = 'Shougo/echodoc.vim'
on_event = ['InsertEnter']
hook_source = """
let g:echodoc#enable_at_startup = 1
let g:echodoc#type = has('nvim') ? 'floating' : 'popup'
highlight link EchoDocFloat Pmenu"""

[plugins."plasticboy/vim-markdown"]
level = 3
repo = "plasticboy/vim-markdown"
on_ft = "markdown"
for = ["markdown","vim-plug"]
hook_source = "source $OVIM_ROOT_PATH/plugins/markdown.vim"

[plugins."iamcco/markdown-preview.nvim"]
level = 3
repo = "iamcco/markdown-preview.nvim"
on_ft = ["markdown","pandoc.markdown","rmd"]
for = ["markdown","pandoc.markdown","rmd","vim-plug"]
build = "sh -c 'cd app && yarn install'"

[plugins."yianwillis/vimcdoc"]
level = 1
repo = "yianwillis/vimcdoc"
on_cmd = ['h','help']
if = "!has('nvim')"

[plugins."sheerun/vim-polyglot"]
level = 3
repo = "sheerun/vim-polyglot"
on_event = ["VimEnter"]
if = 0

[plugins."tpope/vim-unimpaired"]
level = 3
repo = "tpope/vim-unimpaired"
on_event = ["VimEnter"]

[plugins."puremourning/vimspector"]
level = 3
repo = "puremourning/vimspector"
on_map = "<Plug>Vimspector"
on_func = ["vimspector#"]
on_cmd = ["VimspectorInstall","VimspectorUpdate"]
on = ["VimspectorInstall","VimspectorUpdate",
        "<Plug>VimspectorContinue","<Plug>VimspectorStop",
        "<Plug>VimspectorRestart","<Plug>VimspectorPause",
        "<Plug>VimspectorToggleBreakpoint","<Plug>VimspectorToggleConditionalBreakpoint",
        "<Plug>VimspectorAddFunctionBreakpoint","<Plug>VimspectorStepOver",
        "<Plug>VimspectorStepInto","<Plug>VimspectorStepOut",
        "<Plug>VimspectorRunToCursor",]
hook_add = "source $OVIM_ROOT_PATH/plugins/vimspector.add.vim"

[plugins."jmcantrell/vim-virtualenv"]
level = 3
repo = "jmcantrell/vim-virtualenv"
on_ft = ["python"]
for = ["python","vim-plug"]
hook_source = "let g:virtualenv_directory = '~/.cache/venv'"

[plugins."lambdalisue/vim-pyenv"]
level = 3
repo = "lambdalisue/vim-pyenv"
on_ft = ["python"]
for = ["python","vim-plug"]
hook_source = """let g:pyenv#auto_assign_ctags = 0
let g:pyenv#auto_activate = 0"""

[plugins."t9md/vim-choosewin"]
level = 3
repo = "t9md/vim-choosewin"
on_event = ["VimEnter"]
on = ["<Plug>(choosewin)"]
on_map = ["<Plug>(choosewin)"]
hook_source = "source $OVIM_ROOT_PATH/plugins/vim-choosewin.source.vim"

#### modules
#if has node,use coc
[modules.autocomplete]
level = 2
name = "autocomplete"
method = "auto"

[modules.search]
level = 2
name = "search"
method = [ "leaderf", "ctrlp", "fzf","far"]
leader_prefix = "s"

#### build-in addons
[addons.common]
level = 0
enable = 1

[addons.keymap]
level = 0
enable = 1

[addons.edit]
level = 0
enable = 1

[addons.window]
level = 0
enable = 1
