hook_source = ""

[var]
python3_host_prog = "~/miniconda3/envs/vim/bin/python"
ovim_plug_manager = 'dein'


[[plugins]]
repo = "arakashic/nvim-colors-solarized"

[[plugins]]
repo = "morhetz/gruvbox"

[[plugins]]
repo = "miconda/lucariox.vim"

[[plugins]]
repo = "https://gitee.com/yelgors/vim-togglemouse.git"
branch = "dev"
rev = "dev"

[[plugins]]
repo = "Shougo/defx.nvim"
do = ":UpdateRemotePlugins"
hook_post_source = "source $OVIM_ROOT_PATH/plugins/defx.vim"

[[plugins]]
repo = "kristijanhusak/defx-git"

[[plugins]]
repo = "kristijanhusak/defx-icons"
on = ['Defx']
on_cmd = ['Defx']

[[plugins]]
repo = "roxma/nvim-yarp"
if = "!has('nvim')"

[[plugins]]
repo = "roxma/vim-hug-neovim-rpc"
if = "!has('nvim')"

[[plugins]]
repo = "vim-airline/vim-airline"
hook_source = "source $OVIM_ROOT_PATH/plugins/airline.vim"

[[plugins]]
repo = "vim-airline/vim-airline-themes"

[[plugins]]
repo = "Yggdroot/indentLine"
hook_source = "source $OVIM_ROOT_PATH/plugins/indentLine.vim"

[[plugins]]
repo = "scrooloose/nerdtree"
on = ["NERDTreeToggle","NERDTree"]
on_cmd = ["NERDTreeToggle","NERDTree"]
hook_add = "source $OVIM_ROOT_PATH/plugins/nerdtree.vim"

[[plugins]]
repo = "scrooloose/nerdcommenter"
hook_add = "source $OVIM_ROOT_PATH/plugins/nerdcomment.vim"
on = ['<Plug>NERDCommenterComment','<Plug>NERDCommenterNested',
        '<Plug>NERDCommenterToggle','<Plug>NERDCommenterMinimal','<Plug>NERDCommenterInvert',
        '<Plug>NERDCommenterSexy','<Plug>NERDCommenterYank',
        '<Plug>NERDCommenterToEOL','<Plug>NERDCommenterAppend',
        '<Plug>NERDCommenterAltDelims','<Plug>NERDCommenterAlignLeft',
        '<Plug>NERDCommenterAlignBoth','<Plug>NERDCommenterUncomment']
on_map = { n = "<Plug>NERDCommenter" }

[[plugins]]
repo = "majutsushi/tagbar"
on = ["Tagbar","TagbarToggle"]
on_cmd = ["Tagbar"]
hook_add = "source $OVIM_ROOT_PATH/plugins/tarbar.vim"

[[plugins]]
repo = "jiangmiao/auto-pairs"
hook_source = "source $OVIM_ROOT_PATH/plugins/auto-pairs.vim"

[[plugins]]
repo = "SirVer/ultisnips"
hook_source = "source $OVIM_ROOT_PATH/plugins/ultisnips.vim"

[[plugins]]
repo = "honza/vim-snippets"

[[plugins]]
repo = "chiel92/vim-autoformat"
on = "Autoformat"
on_cmd = "Autoformat"
hook_add = "source $OVIM_ROOT_PATH/plugins/autoformat.vim"


[[plugins]]
repo = "skywind3000/asyncrun.vim"
hook_add = "source $OVIM_ROOT_PATH/plugins/asyncrun.vim"
on = ['AsyncRun']
on_cmd = ['AsyncRun']

# [[plugins]]
# repo = "Yggdroot/LeaderF"
# hook_add = "source $OVIM_ROOT_PATH/plugins/leaderf.vim"
# on = ['Leaderf','LeaderfFile','LeaderfBuffer',
#         'LeaderfBufferAll',"LeaderfMru","LeaderfMruCwd",
#         "LeaderfTag","LeaderfBufTag","LeaderfBufTagAll",
#         "LeaderfFunction","LeaderfFunctionAll"]
# on_cmd = ['Leaderf','LeaderfFile','LeaderfBuffer',
#         'LeaderfBufferAll',"LeaderfMru","LeaderfMruCwd",
#         "LeaderfTag","LeaderfBufTag","LeaderfBufTagAll",
#         "LeaderfFunction","LeaderfFunctionAll"]

# [[plugins]]
# repo = "ctrlpvim/ctrlp.vim"
# hook_add = "source $OVIM_ROOT_PATH/plugins/ctrlp.vim"
# on = ["CtrlP","CtrlPFunky"]
# on_cmd = ["CtrlP","CtrlPFunky"]

# [[plugins]]
# repo = "tacahiroy/ctrlp-funky"
# on = ["CtrlP","CtrlPFunky"]
# on_cmd = ["CtrlP","CtrlPFunky"]

[[plugins]]
repo = "pseewald/vim-anyfold"
hook_source = "source $OVIM_ROOT_PATH/plugins/fold.vim"

[[plugins]]
repo = "roxma/vim-paste-easy"

[[plugins]]
repo = "tpope/vim-surround"

[[plugins]]
repo = "ludovicchabant/vim-gutentags"
hook_source = "source $OVIM_ROOT_PATH/plugins/gutentags.vim"
on_event = [ "BufReadPost", "BufWritePost" ]

[[plugins]]
repo = "mhinz/vim-signify"
hook_add = "source $OVIM_ROOT_PATH/plugins/signify.vim"
on = ['SignifyDiff']
on_cmd = ['SignifyDiff']

[[plugins]]
repo = "liuchengxu/vim-which-key"
hook_post_source = "source $OVIM_ROOT_PATH/plugins/vim-which-key.vim"

[[plugins]]
repo = "voldikss/vim-floaterm"
hook_add = "source $OVIM_ROOT_PATH/plugins/floaterm.vim"
on = ['FloatermToggle','FloatermPrev','FloatermNext',
        'FloatermNew','FloatermFirst','FloatermLast','FloatermKill']
on_cmd = ['FloatermToggle','FloatermPrev','FloatermNext',
        'FloatermNew','FloatermFirst','FloatermLast','FloatermKill']

[[plugins]]
repo = "liuchengxu/vista.vim"
hook_add = "source $OVIM_ROOT_PATH/plugins/vista.vim"


# [[plugins]]
# repo = "yianwillis/vimcdoc"
# if = "!has('nvim')"

[[plugins]]
repo = "tweekmonster/startuptime.vim"
on = "StartupTime"
on_cmd = "StartupTime"

[[plugins]]
repo = "wsdjeg/dein-ui.vim"
if = "g:ovim_plug_manager ==# 'dein'"
on_cmd = 'DeinUpdate'

[[plugins]]
repo = "haya14busa/dein-command.vim"
if = "g:ovim_plug_manager ==# 'dein'"
on_cmd = 'Dein'

[[modules]]
name = "autocomplete"
method = "deoplete"

[[modules]]
name = "search"
method = ['leaderf','ctrlp']

